In [1]:
import pandas as pd
import numpy as np
import data_completion_methods as daco
import data_augmentation_methods as daaug
import util
PATH_SAVE = 'augmented_data/'
PATH_AUTOCOMPLETE = 'autocomplete_data/'
PATH_DEFAULT = 'default_values/'

In [10]:
original_data = pd.read_csv(f'{PATH_AUTOCOMPLETE}completed_data__C01__01.csv', index_col=0)
dieds = original_data[original_data['estado_vital'] == 1]
dieds

,estado_vital,edad,sexo,peso,hipertension_arterial,diabetes_mellitus,tabaquismo,frecuencia_cardiaca,presion_arterial_sistolica,presion_arterial_diastolica,hb,creatinina,ckmb,fibrilacion_auricular,insuficiencia_renal_cronica,ieca,furosemida,otros_diureticos,clopidogrel
98,1.0,47.0,1.0,65.0,1.0,0.0,1.0,124.0,70.0,50.0,150.0,57.0,47.39,0.0,0.0,1.0,0.0,0.0,1.0
175,1.0,52.0,1.0,80.0,1.0,0.0,1.0,44.0,80.0,60.0,134.0,88.0,112.00,0.0,0.0,0.0,0.0,0.0,1.0
188,1.0,52.0,1.0,90.0,1.0,1.0,1.0,84.0,110.0,70.0,125.0,132.0,1.00,0.0,0.0,1.0,1.0,0.0,1.0
253,1.0,54.0,0.0,70.0,1.0,0.0,1.0,88.0,80.0,50.0,133.0,133.0,166.00,0.0,0.0,0.0,1.0,0.0,1.0
308,1.0,56.0,1.0,90.0,1.0,1.0,0.0,90.0,110.0,70.0,8.0,130.0,47.39,0.0,0.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1340,1.0,91.0,0.0,81.0,1.0,1.0,0.0,87.0,130.0,70.0,94.0,84.0,184.70,0.0,0.0,1.0,0.0,0.0,1.0
1341,1.0,91.0,0.0,50.0,1.0,0.0,0.0,83.0,120.0,70.0,122.0,115.0,152.00,0.0,0.0,1.0,0.0,1.0,1.0
1345,1.0,93.0,1.0,60.0,1.0,0.0,0.0,76.0,130.0,70.0,133.0,88.0,184.00,0.0,0.0,1.0,0.0,1.0,1.0
1347,1.0,94.0,1.0,95.0,1.0,1.0,0.0,43.0,80.0,50.0,134.0,120.0,143.00,0.0,0.0,0.0,1.0,0.0,1.0
1351,1.0,96.0,0.0,65.0,1.0,0.0,0.0,56.0,110.0,70.0,114.0,149.0,184.70,0.0,0.0,1.0,1.0,0.0,1.0

In [3]:
new_dieds = daaug.create_many_mod_record_from_json(1000,dieds,'augmented_data/feature_augmented__01.json')
new_dieds.reset_index(0,drop=True, inplace=True)
new_dieds

,estado_vital,edad,sexo,peso,hipertension_arterial,diabetes_mellitus,tabaquismo,frecuencia_cardiaca,presion_arterial_sistolica,presion_arterial_diastolica,hb,creatinina,ckmb,fibrilacion_auricular,insuficiencia_renal_cronica,ieca,furosemida,otros_diureticos,clopidogrel
0,1.0,81.505475,1.0,82.126742,1.0,1.0,0.0,84.626967,113.442791,64.753518,133.251989,145.561033,147.394118,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,77.786634,1.0,68.801044,1.0,0.0,0.0,66.890598,110.776949,79.494474,147.896589,112.205978,184.707556,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,62.348576,0.0,69.019663,1.0,0.0,0.0,63.438503,100.795449,56.862169,129.590717,112.503438,187.861012,0.0,0.0,1.0,0.0,0.0,1.0
3,1.0,65.430016,1.0,59.513622,1.0,0.0,1.0,111.191221,78.981302,47.608235,149.474878,104.613554,183.467078,0.0,0.0,0.0,0.0,0.0,1.0
4,1.0,93.560551,0.0,63.231315,1.0,0.0,0.0,53.637770,118.006637,76.315217,112.086405,150.599535,181.226541,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.0,63.047684,1.0,92.051010,1.0,1.0,1.0,97.197443,122.133539,68.423883,123.521396,92.419319,181.735449,0.0,0.0,1.0,0.0,1.0,1.0
996,1.0,71.047275,1.0,56.060858,1.0,0.0,1.0,88.814019,129.373263,64.604706,139.548472,126.291746,160.119821,0.0,0.0,1.0,0.0,0.0,1.0
997,1.0,95.247840,1.0,63.614672,1.0,0.0,0.0,78.498103,132.116558,78.531454,135.061545,88.426143,186.545758,0.0,0.0,1.0,0.0,1.0,1.0
998,1.0,79.570515,1.0,75.746054,0.0,1.0,1.0,102.668264,74.061754,37.608717,136.792390,163.261416,105.694073,0.0,0.0,0.0,0.0,0.0,1.0
999,1.0,92.010039,1.0,61.413974,1.0,0.0,0.0,75.642794,136.830450,65.192740,130.024729,86.630809,184.721932,0.0,0.0,1.0,0.0,1.0,1.0

In [4]:
mezclado = pd.concat([original_data, new_dieds])
mezclado.reset_index(0,drop=True, inplace=True)
mezclado

,estado_vital,edad,sexo,peso,hipertension_arterial,diabetes_mellitus,tabaquismo,frecuencia_cardiaca,presion_arterial_sistolica,presion_arterial_diastolica,hb,creatinina,ckmb,fibrilacion_auricular,insuficiencia_renal_cronica,ieca,furosemida,otros_diureticos,clopidogrel
0,0.0,13.000000,0.0,85.000000,1.0,0.0,0.0,60.000000,120.000000,70.000000,136.000000,70.000000,369.000000,0.0,0.0,1.0,0.0,1.0,1.0
1,0.0,15.000000,0.0,57.000000,1.0,1.0,1.0,95.000000,120.000000,70.000000,129.000000,105.000000,145.000000,0.0,0.0,1.0,0.0,0.0,1.0
2,0.0,19.000000,0.0,65.000000,1.0,0.0,0.0,67.000000,120.000000,80.000000,108.000000,61.000000,184.700000,0.0,0.0,0.0,1.0,0.0,1.0
3,0.0,23.000000,1.0,70.000000,1.0,0.0,0.0,88.000000,120.000000,70.000000,133.000000,81.000000,187.000000,0.0,0.0,1.0,0.0,1.0,1.0
4,0.0,28.000000,1.0,75.000000,1.0,0.0,1.0,77.000000,160.000000,100.000000,135.000000,74.000000,184.700000,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2348,1.0,63.047684,1.0,92.051010,1.0,1.0,1.0,97.197443,122.133539,68.423883,123.521396,92.419319,181.735449,0.0,0.0,1.0,0.0,1.0,1.0
2349,1.0,71.047275,1.0,56.060858,1.0,0.0,1.0,88.814019,129.373263,64.604706,139.548472,126.291746,160.119821,0.0,0.0,1.0,0.0,0.0,1.0
2350,1.0,95.247840,1.0,63.614672,1.0,0.0,0.0,78.498103,132.116558,78.531454,135.061545,88.426143,186.545758,0.0,0.0,1.0,0.0,1.0,1.0
2351,1.0,79.570515,1.0,75.746054,0.0,1.0,1.0,102.668264,74.061754,37.608717,136.792390,163.261416,105.694073,0.0,0.0,0.0,0.0,0.0,1.0
2352,1.0,92.010039,1.0,61.413974,1.0,0.0,0.0,75.642794,136.830450,65.192740,130.024729,86.630809,184.721932,0.0,0.0,1.0,0.0,1.0,1.0

In [5]:
mezclado.to_csv(f'{PATH_SAVE}augmented_data__C01__01__F01.csv')

In [6]:
original_data = pd.read_csv(f'{PATH_AUTOCOMPLETE}completed_data__C01__02.csv', index_col=0)
dieds = original_data[original_data['estado_vital'] == 1]
new_dieds = daaug.create_many_mod_record_from_json(1000,dieds,'augmented_data/feature_augmented__01.json')
new_dieds.reset_index(0,drop=True, inplace=True)
mezclado = pd.concat([original_data, new_dieds])
mezclado.reset_index(0,drop=True, inplace=True)

In [7]:
mezclado.to_csv(f'{PATH_SAVE}augmented_data__C01__02__F01.csv')

In [8]:
original_data = pd.read_csv(f'{PATH_AUTOCOMPLETE}completed_data__C01__03.csv', index_col=0)
dieds = original_data[original_data['estado_vital'] == 1]
new_dieds = daaug.create_many_mod_record_from_json(1000,dieds,'augmented_data/feature_augmented__01.json')
new_dieds.reset_index(0,drop=True, inplace=True)
mezclado = pd.concat([original_data, new_dieds])
mezclado.reset_index(0,drop=True, inplace=True)

In [9]:
mezclado.to_csv(f'{PATH_SAVE}augmented_data__C01__03__F01.csv')